# Generated by Django 3.1.7 on 2021-05-05 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.CharField(max_length=100, unique=True)),
                ('problem_name', models.CharField(max_length=100, unique=True)),
                ('Problem_text', models.TextField()),
                ('sample_input', models.CharField(max_length=255, null=True)),
                ('sample_output', models.CharField(max_length=255, null=True)),
                ('input', models.FileField(null=True, upload_to='Documents/TestCase/Input')),
                ('output', models.FileField(null=True, upload_to='Documents/TestCase/Output')),
                ('category', models.CharField(choices=[('Input-Output', 'Input-Output'), ('Basic Python', 'Basic Python'), ('Conditionals', 'Conditionals'), ('Loops & Array', 'Loops & Array'), ('Function', 'Function'), ('Class & Objects', 'Class & Objects'), ('File Handling', 'File Handling')], max_length=100, null=True)),
                ('level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20, null=True)),
                ('setter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
