# Generated by Django 3.1.7 on 2021-04-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.CharField(max_length=20, unique=True)),
                ('problem_name', models.CharField(max_length=30, unique=True)),
                ('Problem_text', models.FileField(upload_to='Documents/Problem')),
                ('input', models.FileField(upload_to='Documents/TestCase/Input')),
                ('output', models.FileField(upload_to='Documents/TestCase/Output')),
                ('category', models.CharField(choices=[('Input-Output', 'Input-Output'), ('String', 'String'), ('Math', 'Math'), ('Set', 'Set')], max_length=20, null=True)),
                ('level', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20, null=True)),
            ],
        ),
    ]
