# Generated by Django 3.1.7 on 2021-04-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='problem_id',
        ),
        migrations.AlterField(
            model_name='problems',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
