# Generated by Django 3.1.7 on 2021-05-22 14:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='Problem_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
