# Generated by Django 3.1.7 on 2021-04-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='input',
            field=models.FileField(null=True, upload_to='Documents/TestCase/Input'),
        ),
    ]
