# Generated by Django 3.1.7 on 2021-05-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0002_auto_20210522_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='category',
            field=models.CharField(choices=[('Basic Python', 'Basic Python'), ('Conditionals', 'Conditionals'), ('Loops & Array', 'Loops & Array'), ('Function', 'Function'), ('Class & Objects', 'Class & Objects'), ('File Handling', 'File Handling')], max_length=100, null=True),
        ),
    ]
