# Generated by Django 3.1.7 on 2021-04-06 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0002_auto_20210406_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='problem_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problems',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
