# Generated by Django 3.1.7 on 2021-10-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Problems', '0003_auto_20210522_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, unique=True)),
                ('problem_id', models.CharField(max_length=100)),
                ('problem_name', models.CharField(max_length=100)),
                ('submission_time', models.CharField(max_length=100, unique=True)),
                ('verdict', models.CharField(max_length=50)),
                ('run_time', models.CharField(max_length=50)),
            ],
        ),
    ]
