# Generated by Django 3.1.7 on 2021-03-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contestant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='email',
            field=models.EmailField(db_column='Email', max_length=30),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='first_name',
            field=models.CharField(db_column='First Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='last_name',
            field=models.CharField(db_column='Last Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='password',
            field=models.CharField(db_column='Password', max_length=20),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='solver_id',
            field=models.CharField(db_column='Solver ID', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='username',
            field=models.CharField(db_column='Username', max_length=10),
        ),
        migrations.AlterModelTable(
            name='contestant',
            table='Contestant',
        ),
    ]
