# Generated by Django 3.1.7 on 2021-04-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contestant', '0002_auto_20210406_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
