# Generated by Django 3.1.7 on 2021-04-03 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Judge', '0001_initial'),
        ('Contestant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=30, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ManyToManyField(to='Contestant.Contestant')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Judge.judge')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=50)),
                ('tutorial_text', models.FileField(upload_to='Documents/Tutorials')),
                ('contest_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Contest.contest')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Judge.judge')),
            ],
        ),
    ]
