# Generated by Django 3.1.7 on 2021-03-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_id', models.CharField(max_length=10)),
                ('tutorial_title', models.CharField(max_length=50)),
                ('tutorial_text', models.FileField(upload_to='Documents/Tutorials')),
            ],
        ),
    ]
