# Generated by Django 3.1.7 on 2021-04-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='contest_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
