# Generated by Django 3.1.7 on 2021-05-22 17:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
